### ISSUE TITLE
Request: Docker container

### ISSUE THREAD

**Issue by docwhat** [chef/dcob#9]
It'd be nice to have an official docker container for this project.

**Comment by thommay** [comment]
you can build it with habitat -> run `hab pkg export docker thom/dcob`

**Comment by thommay** [comment]
Given the above, I'm not intending to do anything else; it would be an afterthought at best and likely to become outdated.

**Comment by docwhat** [comment]
FYI: I wanted an official container so I could just do `docker pull chef/dcob` and be able to keep up with the latest version.

Having to install habitat and setup cron jobs to periodically do a `git pull` and `hab pkg export...` isn't "easy".  I don't have a full Habitat installation to make use of.
